#############################################################################
## Cassandra Configuration
#############################################################################
#spring:
#  data:
#    cassandra:
#      keyspace-name: football_transfers
#      contact-points: 127.0.0.1
#      port: 9142
#      username: cassandra
#      password: cassandra
#      consistency-level: quorum
#      serial-consistency-level: quorum

endpoint:
  teams: http://localhost:9078
  players: http://localhost:9072